### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text_to_sequence'

### ISSUE THREAD

**Issue by johnbie** [r9y9/deepvoice3_pytorch#37] opened 2018-02-04 21:57 UTC
When I try to train a dataset with the command from the tutorial (python train.py --data-root=./data/ljspeech/ --hparams="builder=deepvoice3,preset=deepvoice3_ljspeech") I get an error telling me that _frontend is a NoneType object and has no 'text_to_sequence' attribute. Do I need to modify anything to get this to work again?

AttributeError: 'NoneType' object has no attribute 'text_to_sequence'

**Comment by sjfischr** [comment] 2018-02-04 22:08
It’s missing some params.
Here’s an example using the pretrained model in a folder named /model, a file named test_lists that contains the text you want to convert to speech, and an output folder for the wave files/graphs.
 
`python3 synthesis.py --hparams="builder=deepvoice3,preset=deepvoice3_ljspeech" model/20171213_deepvoice3_checkpoint_step000210000.pth test_lists.txt tests`

**Comment by johnbie** [comment] 2018-02-04 23:58
I wasn't expecting to synthesize an audio file just yet. 

The command you sent me also doesn't work, but for a different reason. Here's the error log I got. I created a test_lists.txt file with text to synthesize on each line.

`
Traceback (most recent call last):
  File "synthesis.py", line 137, in <module>
    model, text, p=replace_pronunciation_prob, speaker_id=speaker_id, fast=True)
  File "synthesis.py", line 66, in tts
    sequence, text_positions=text_positions, speaker_ids=speaker_ids)
  File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Projects\TTS-Tacotron\deepvoice3_pytorch-master\deepvoice3_pytorch\__init__.py", line 79, in forward
    text_positions, frame_positions, input_lengths)
  File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Projects\TTS-Tacotron\deepvoice3_pytorch-master\deepvoice3_pytorch\__init__.py", line 116, in forward
    text_sequences, lengths=input_lengths, speaker_embed=speaker_embed)
  File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Projects\TTS-Tacotron\deepvoice3_pytorch-master\deepvoice3_pytorch\deepvoice3.py", line 75, in forward
    x = self.embed_tokens(text_sequences)
  File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\site-packages\torch\nn\modules\sparse.py", line 103, in forward
    self.scale_grad_by_freq, self.sparse
  File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\site-packages\torch\nn\_functions\thnn\sparse.py", line 59, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.cuda.IntTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)
`

and here's the test_list.txt file:
`
howdy ho ready i am doctor
what is it what is it not the bees not the bees
I'm a vampire
I'm like a prickly pear
I'm a prickly pear
What the fuck is this shit
`

**Comment by r9y9** [comment] 2018-02-05 01:11
That's strange. Did you change the frontend in hparams? https://github.com/r9y9/deepvoice3_pytorch/blob/9ed221424ed2ba39a69c028399624cc41df965ba/hparams.py#L10-L12

**Comment by johnbie** [comment] 2018-02-05 01:44
The frontend is the same as what is written on your comment. should it be different?

**Comment by r9y9** [comment] 2018-02-05 03:29
It should be `en` if you are using LJSpeech. Can you try the following code and see if it works?

```py
In [1]: import deepvoice3_pytorch

In [2]: from deepvoice3_pytorch.frontend import en

In [3]:  en.n_vocab
Out[3]: 149

In [4]: deepvoice3_pytorch.__version__
Out[4]: '0.0.3+446039d'
```

**Comment by r9y9** [comment] 2018-02-05 03:31
If it works, https://github.com/r9y9/deepvoice3_pytorch/blob/9ed221424ed2ba39a69c028399624cc41df965ba/train.py#L884 should not be `None`...

**Comment by johnbie** [comment] 2018-02-05 04:49
I previously commented out "from .version import __version__" in "deepvoice3_pytorch/__init__.py" file because python kept returning an import  error (module not found). I think that might have something to do with it. I was unable to run the forth command on the python terminal (deepvoice3_pytorch.__version__) but was able to run everything else from it. Where is the deepvoice3_pytorch.version package?

For my copy of the code, _frontend was defined as None in line 65 and defined later as "frontend = getattr(frontend, hparams.frontend)" in line 876. Should I try getting the latest version of the code?

**Comment by r9y9** [comment] 2018-02-05 05:00
Okay, the problem is that you didn't install the package. Please follow the installation guide. https://github.com/r9y9/deepvoice3_pytorch#installation. `version.py` will be generated durning installation. I'd recommend the latest version, but `pip install deepvoice3_pytorch` should work as well.

**Comment by johnbie** [comment] 2018-02-05 05:37
I tried both methods, but I'm getting an ambiguous error. Part of the problem is that I'm using Windows, and there were several hurdles involved because of it. Do you know what this might mean?

Obtaining file:///D:/Projects/TTS-Tacotron/deepvoice3_pytorch-master
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Projects\TTS-Tacotron\deepvoice3_pytorch-master\setup.py", line 19, in <module>
        ['git', 'rev-parse', 'HEAD'], cwd=cwd).decode('ascii').strip()
      File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\subprocess.py", line 316, in check_output
        **kwargs).stdout
      File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\subprocess.py", line 383, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\subprocess.py", line 957, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by r9y9** [comment] 2018-02-05 05:55
I fixed the particular problem, thank you.  However, I'd recommend Linux unless you are sure you can solve the problems yourself. Some dependencies also have problems on WIndows. (https://github.com/r9y9/nnmnkwii/issues/66, https://github.com/MattShannon/bandmat/pull/6).

If you want to continue work on Windows, you might try the following commands:

```
conda install cython
pip install git+https://github.com/r9y9/bandmat@ci
pip install git+https://github.com/r9y9/nnmnkwii
pip install git+https://github.com/r9y9/deepvoice3_pytorch
```

I believe this should work on Windows. I mean, no errors happen at install time.

**Comment by johnbie** [comment] 2018-02-05 06:20
Thank you for the fix. I am now able to run training on windows, but have yet to synthesize anything due to the same bug mentioned above. I'm going to look over this tomorrow. I suspect that the solution is not something that's too complicated. I'll let you know if I continue experiencing problems.

**Comment by r9y9** [comment] 2018-02-05 06:38
I'm not sure PyTorch is supported on WIndows. As far as I can tell from the error message, 

> TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.cuda.IntTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)

There's IntTensor somewhere, though LongTensor is expected. I suspect you are on 32-bit system? We may have to convert some tensors to type LongTensor explicitly. i.e., `tensor = tensor.long()`.

**Comment by johnbie** [comment] 2018-02-05 17:46
The machine is 64 bit. If anything, I believe one of the packages are causing 32bit to run. Might be bandmat because I was having some trouble installing it on my computer.

**Comment by johnbie** [comment] 2018-02-05 17:48
Training doesn't seem to work either. The logs folder only has events.out.tfevents files and failed because of memory error.

Los event path: log/run-test2018-02-05_06-21-18.233857
819it [07:58,  1.34it/s]
Loss: 0.5317149023287754
819it [07:57,  1.34it/s]
Loss: 0.3216093134166848
819it [07:57,  1.34it/s]
Loss: 0.28948061595760716
819it [07:55,  1.34it/s]
Loss: 0.27628320753938257
819it [07:55,  1.34it/s]
Loss: 0.2665114902933293
36it [00:21,  1.53it/s]Traceback (most recent call last):
  File "train.py", line 939, in <module>
    train_seq2seq=train_seq2seq, train_postnet=train_postnet)
  File "train.py", line 576, in train
    in tqdm(enumerate(data_loader)):
  File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\site-packages\tqdm\_tqdm.py", line 833, in __iter__
    for obj in iterable:
  File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\site-packages\torch\utils\data\dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\site-packages\torch\utils\data\dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
MemoryError: Traceback (most recent call last):
  File "C:\Users\mwc2018\Anaconda3\envs\tensorflow\lib\site-packages\torch\utils\data\dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Projects\TTS-Tacotron\deepvoice3_pytorch-master\train.py", line 320, in collate_fn
    dtype=np.float32)
MemoryError

**Comment by amilamad** [comment] 2018-03-03 06:29
I think have figured the problem.
In synthesis.py, 
Find the line 
sequence = Variable(torch.from_numpy(sequence)).unsqueeze(0)
and replace it with 
sequence = Variable(torch.from_numpy(sequence)).unsqueeze(0).long()

**Comment by r9y9** [comment] 2018-03-03 06:56
@amilamad I don't think it's related to the issue. What are you trying to solve?

**Comment by amilamad** [comment] 2018-03-03 14:35
I`m talking about the,
`TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.cuda.IntTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)`
issue.
I got the same issue with the LJ data branch and master. After
`sequence = Variable(torch.from_numpy(sequence)).unsqueeze(0).long()`
it generated voice output for given text with good qulaity on windows.

And thanks for this open source project.  I have tried few ML based tts projects and this gives me very good results.  :)

**Comment by r9y9** [comment] 2018-03-03 14:38
@amilamad Nice! That looks good to me. Would you like to create a PR?

**Comment by amilamad** [comment] 2018-03-04 03:55
@r9y9 Sure, I will

**Comment by MattShannon** [comment] 2018-06-05 11:19
Hopefully windows-specific issues with bandmat should now be fixed.

**Comment by r9y9** [comment] 2018-06-06 15:07
I'm closing this issue. Feel free to reopen if you still see the issue.

**Closed by r9y9** 2018-06-06 15:07 UTC
Labels: windows

**Comment by YYYYWD** [comment] 2019-09-18 17:59
Hi! I meet the same problem about "AttributeError: 'NoneType' object has no attribute 'text_to_sequence'" Could you help me?
