### ISSUE TITLE
ModuleNotFoundError: No module named '_version' when importing lws

### ISSUE THREAD

**Issue by sdx0112** [r9y9/deepvoice3_pytorch#164] opened 2019-07-08 13:43 UTC
I downloaded LJSpeech data and tried the preprocess step: `python preprocess.py --preset=presets/deepvoice3_ljspeech.json ljspeech ~/data/LJSpeech-1.0/ ./data/ljspeech`.
Here is the error:
```
Traceback (most recent call last):
  File "preprocess.py", line 58, in <module>
    mod = importlib.import_module(name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\DeepFake\voice\deepvoice3_pytorch\ljspeech.py", line 5, in <module>
    import audio
  File "D:\DeepFake\voice\deepvoice3_pytorch\audio.py", line 9, in <module>
    import lws
  File "lws.pyx", line 6, in init lws
ModuleNotFoundError: No module named '_version'
```
I did some research on this error. The reason seems to be that python3 does not support `from _version import __version__`. But I didn't manage to fix it.

**Comment by r9y9** [comment] 2019-07-08 13:57
Looks like the problem comes from lws. Please report to https://github.com/Jonathan-LeRoux/lws.

**Comment by r9y9** [comment] 2019-07-09 01:53
Looks like https://github.com/Jonathan-LeRoux/lws/issues/8

**Comment by Jonathan-LeRoux** [comment] 2019-07-10 00:50
Yes, sorry for the annoyances, the problem should now be fixed.

**Comment by r9y9** [comment] 2019-07-10 02:16
I confirmed this is fixed now. Thanks!

**Closed by r9y9** 2019-07-10 02:16 UTC
